zip 3.1d25_l_s6x Beta
Origin: http://antinode.info/ftp/info-zip//zip31d25_l_s6x.zip

diff --git a/unix/configure b/unix/configure
--- a/unix/configure
+++ b/unix/configure
@@ -4,7 +4,7 @@
 
 #==============================================================================
 # unix/configure: Detect feature support and pass that information to Makefile.
-# - For Zip, ZipNote, ZipCloak and ZipSplit            Last update: 10 Apr 2012
+# - For Zip, ZipNote, ZipCloak and ZipSplit            Last update: 06 Jul 2012
 #==============================================================================
 
 #==============================================================================
@@ -94,8 +94,10 @@
 #    LFLAGS2     - Linker flag initial values (after output file spec)
 #
 #    OSDEP_H     - OS-dependent C header file names
-#    OSDEP_OC    - OS-dependent C object file names
-#    OSDEP_OS    - OS-dependent Assembler object file names
+#    OSDEP_OCU   - OS-dependent C object file names for utilities
+#    OSDEP_OCZ   - OS-dependent C object file names for zip
+#    OSDEP_OSU   - OS-dependent Assembler object file names for utilities
+#    OSDEP_OSZ   - OS-dependent Assembler object file names for zip
 #
 #    PGMEXT      - Binary program file extension
 #    DLLEXT      - Binary program DLL (.so) file extension
@@ -106,6 +108,7 @@
 #    AES_WG      - Enable AES encryption (WinZip/Gladman)
 #    IZ_BZIP2    - Enable BZIP2 compression
 #    IZ_ZLIB     - Use ZLIB for deflate compression
+#    LIBZIP      - Build Zip object library
 #    LZMA        - Enable LZMA compression
 #    PPMD        - Enable PPMd compression
 #
@@ -138,10 +141,13 @@
 #  LIB_LZMA    - LZMA compression build dependencies
 #  LIB_PPMD    - PPMd compression build dependencies
 #  LIB_Z       - ZLIB compression build dependencies
+#  LIB_ZIP     - Zip object library
 #  MK_BZ       - BZIP2 compression build makefile
 #  OSDEP_H     - OS-dependent C header file names
-#  OSDEP_OC    - OS-dependent C object file names
-#  OSDEP_OS    - OS-dependent Assembler object file names
+#  OSDEP_OCU   - OS-dependent C object file names for utilities
+#  OSDEP_OCZ   - OS-dependent C object file names for zip
+#  OSDEP_OSU   - OS-dependent Assembler object file names for utilities
+#  OSDEP_OSZ   - OS-dependent Assembler object file names for zip
 #  PGMEXT      - Binary program file extension
 #  DLLEXT      - Binary program DLL (.so) file extension
 #  BINDIR      - Binary program installation directory
@@ -161,10 +167,11 @@ echo ''
 echo 'Generating system-dependent flags...'
 
 # Evaluate only variables in this list.  Complain about others, but continue.
-valid_vars1="|AES_WG|AFLAGS|AS|CC|CC_BZ|CFLAGS|CPP|DLLEXT|IZ_BZIP2|IZ_ZLIB"
-valid_vars2="|LD|LFLAGS1|LFLAGS2|LIST|LOCAL_ZIP|LZMA"
-valid_vars3="|OSDEP_H|OSDEP_OC|OSDEP_OS|PGMEXT|PPMD|PROD|RANLIB|"
-valid_vars="${valid_vars1}${valid_vars2}${valid_vars3}"
+valid_vars1='|AES_WG|AFLAGS|AS|CC|CC_BZ|CFLAGS|CPP|DLLEXT|IZ_BZIP2|IZ_ZLIB'
+valid_vars2='|LD|LFLAGS1|LFLAGS2|LIST|LOCAL_ZIP|LZMA'
+valid_vars3='|OSDEP_H|OSDEP_OCU|OSDEP_OCZ|OSDEP_OSU|OSDEP_OSZ'
+valid_vars4='|PGMEXT|PPMD|PROD|RANLIB|'
+valid_vars="${valid_vars1}${valid_vars2}${valid_vars3}${valid_vars4}"
 
 argc=$#
 while [ ${argc} -gt 0 ]; do
@@ -243,6 +250,7 @@ LIB_BZ=''                                  # BZIP2 compression
 LIB_LZMA=''                                # LZMA compression
 LIB_PPMD=''                                # PPMd compression
 LIB_Z=''                                   # ZLIB compression
+LIB_ZIP=''                                 # Zip object library
 
 # Build makefiles.
 MK_BZ='Makefile'                           # BZIP2 compression
@@ -250,8 +258,10 @@ MK_BZ='Makefile'                           # BZIP2 compression
 # OS-dependent files.
 # Defaults to unix files, customized based on PORT and tests.
 OSDEP_H=${OSDEP_H:-'unix/osdep.h'}         # C header file names
-OSDEP_OC=${OSDEP_OC:-"${PROD}/unix.o"}     # C object file names
-OSDEP_OS=${OSDEP_OS:-}                     # Assembler object file names
+OSDEP_OCU=${OSDEP_OCU:-"${PROD}/unix.o"}   # C object file names, utilities
+OSDEP_OCZ=${OSDEP_OCZ:-"${PROD}/unix.o"}   # C object file names, zip
+OSDEP_OSU=${OSDEP_OSU:-}                   # Asm object file names, utilities
+OSDEP_OSZ=${OSDEP_OSZ:-}                   # Asm object file names, zip
 
 # OS-dependent file extensions.
 # Defaults to unix files, customized based on PORT and tests.
@@ -501,6 +511,7 @@ _EOF_
   status=$?
   if [ $status -eq 0 ]; then
     CFLAGS_OPT='-O3'
+    PORT='mingw64'
     echo "  MinGW 64 ($CFLAGS_OPT)"
   fi
 fi
@@ -521,6 +532,7 @@ _EOF_
   status=$?
   if [ $status -eq 0 ]; then
     CFLAGS_OPT='-O3'
+    PORT='mingw32'
     echo "  MinGW 32 ($CFLAGS_OPT)"
   fi
 fi
@@ -1031,56 +1043,78 @@ if [ "${PORT}" = "unix" ]; then
 else
   echo "Set build configuration for target \"${PORT}\" port"
   case "${PORT}" in
-     'unix' )
+     unix )
         # UNIX values set in defaults, customized based on tests.
         ;;
 
-     'msdos' )
+     mingw* )
+        CFLAGS="${CFLAGS} -DWIN32"
+        CFLAGS_BZ="${CFLAGS_BZ} -D_WIN32"
+        OSDEP_H='win32/osdep.h win32/zipup.h'
+        OSDEP_OCU="${PROD}/win32.o ${PROD}/win32i64.o"
+        OSDEP_OCZ="${PROD}/nt.o ${OSDEP_OCU} ${PROD}/win32zip.o"
+        OSDEP_OSU=''
+        OSDEP_OSZ=''
+        PGMEXT='.exe'
+        DLLEXT='.dll'
+        ;;
+
+     msdos )
         CFLAGS="${CFLAGS} -DMSDOS"
         CFLAGS_BZ="${CFLAGS_BZ} -DMSDOS"
         OSDEP_H='msdos/osdep.h msdos/zipup.h'
-        OSDEP_OC="${PROD}/msdos.o"
-        OSDEP_OS=''
+        OSDEP_OCU="${PROD}/msdos.o"
+        OSDEP_OCZ="${PROD}/msdos.o"
+        OSDEP_OSU=''
+        OSDEP_OSZ=''
         PGMEXT='.EXE'
         DLLEXT='.DLL'
         ;;
 
-     'os2' )
+     os2 )
         CFLAGS="${CFLAGS} -DOS2"
         CFLAGS_BZ="${CFLAGS_BZ} -DOS2"
         OSDEP_H='os2/os2acl.h  os2/os2zip.h  os2/osdep.h  os2/zipup.h'
-        OSDEP_OC="${PROD}/os2.o"
-        OSDEP_OS=''
+        OSDEP_OCU="${PROD}/os2.o"
+        OSDEP_OCZ="${PROD}/os2.o"
+        OSDEP_OSU=''
+        OSDEP_OSZ=''
         PGMEXT='.EXE'
         DLLEXT='.DLL'
         ;;
 
-     'qdos' )
+     qdos )
         CFLAGS="${CFLAGS} -DQDOS"
         CFLAGS_BZ="${CFLAGS_BZ} -DQDOS"
         OSDEP_H='qdos/osdep.h  qdos/zipup.h'
-        OSDEP_OC="${PROD}/qdos.o ${PROD}/qfileio.o"
-        OSDEP_OS=''
+        OSDEP_OCU="${PROD}/qdos.o ${PROD}/qfileio.o"
+        OSDEP_OCZ="${PROD}/qdos.o ${PROD}/qfileio.o"
+        OSDEP_OSU=''
+        OSDEP_OSZ=''
         PGMEXT=''
         DLLEXT=''
         ;;
 
-     'zos' )
+     zos )
         CFLAGS="${CFLAGS} -DMVS"
         CFLAGS_BZ="${CFLAGS_BZ} -DMVS"
         OSDEP_H='zos/cmsmvs.h  zos/mvs.h  zos/zipup.h'
-        OSDEP_OC="${PROD}/mvs.o"
-        OSDEP_OS=''
+        OSDEP_OCU="${PROD}/mvs.o"
+        OSDEP_OCZ="${PROD}/mvs.o"
+        OSDEP_OSU=''
+        OSDEP_OSZ=''
         PGMEXT=''
         DLLEXT=''
         ;;
 
-     'zvm' )
+     zvm )
         CFLAGS="${CFLAGS} -DVM_CMS"
         CFLAGS_BZ="${CFLAGS_BZ} -DVM_CMS"
         OSDEP_H='zvm/cstat.h zos/cmsmvs.h  zos/zipup.h'
-        OSDEP_OC="${PROD}/cms.o"
-        OSDEP_OS=''
+        OSDEP_OCU="${PROD}/cms.o"
+        OSDEP_OCZ="${PROD}/cms.o"
+        OSDEP_OSU=''
+        OSDEP_OSZ=''
         PGMEXT=''
         DLLEXT=''
         ;;
@@ -1137,38 +1171,80 @@ case "${UNAME_S}" in
    *  )
       # Other UNIX systems.
       # FIX_ME: Need to customize for ports.
-      echo 'Check if we can use assembler match and CRC code'
-      if eval "$CPP_TST match.S > _match.s 2>/dev/null"; then
-        if [ -s _match.s ]; then
-          :
-        elif [ grep error < _match.s >/dev/null ]; then
-          :
-        elif eval "$CC -c  _match.s >/dev/null 2>/dev/null" \
-            && [ -f _match.o ]; then
-          # Check if CPP output builds directly with gcc
-          echo '-- Using assembler match code'
-          CFLAGS_TST="${CFLAGS_TST} -DASMV"
-          OSDEP_OS="${OSDEP_OS} ${PROD}/mch_gcc.o"
-
-          if eval "$CPP_TST crc_i386.S > _crc_i386.s 2>/dev/null"; then
-            # Check if CPP output builds directly with gcc
-            if eval "$CC -c _crc_i386.s >/dev/null 2>/dev/null" \
-                && [ -f _crc_i386.o ]; then
-              echo '-- Using assembler CRC code'
-              CFLAGS_TST="${CFLAGS_TST} -DASM_CRC"
-              OSDEP_OS="${OSDEP_OS} ${PROD}/crc_gcc.o"
-            fi
-          fi
-
-          echo 'Check if compiler generates underlines (CPP, for .S)'
-          echo "int foo() { return 0;}" > conftest.c
-          $AS conftest.c >/dev/null 2>/dev/null
-          nm conftest.o | grep "(^|[^_])foo" >/dev/null 2>/dev/null
+      echo 'Check if we can (and want to) use assembly code for CRC and match'
+      asm_crc=0
+      asmv=0
+      # CRC.  Fail intentionally, if NO_ASM or NO_ASM_CRC is defined.
+      cat > conftest.S << _EOF_
+#if defined( NO_ASM) || defined( NO_ASM_CRC)
+    bad code
+#else
+# include "crc_i386.S"
+#endif
+_EOF_
+      ${CPP_TST} ${CFLAGS} conftest.S > _crc_i386.s 2> /dev/null
+      status=$?
+      if [ $status -eq 0 -a -s _crc_i386.s ]; then
+        grep error _crc_i386.s > /dev/null
+        status=$?
+        if [ $status -ne 0 ]; then
+          $CC -c _crc_i386.s > /dev/null 2> /dev/null
           status=$?
-          [ $status -eq 0 ] && CPP="${CPP} -DNO_UNDERLINE"
+          if [ $status -eq 0 -a -f _crc_i386.o ]; then
+            echo '-- Using assembly code for CRC'
+            asm_crc=1
+            CFLAGS_TST="${CFLAGS_TST} -DASM_CRC"
+            OSDEP_OSU="${OSDEP_OSU} ${PROD}/crc_gcc.o"
+            OSDEP_OSZ="${OSDEP_OSZ} ${PROD}/crc_gcc.o"
+          fi
         fi
       fi
-      rm -f _match.s _match.o _crc_i386.s _crc_i386.o
+      # Match.  Fail intentionally, if NO_ASM or NO_ASMV is defined.
+      cat > conftest.S << _EOF_
+#if defined( NO_ASM) || defined( NO_ASMV)
+    bad code
+#else
+# include "match.S"
+#endif
+_EOF_
+      ${CPP_TST} ${CFLAGS} conftest.S > _match.s 2> /dev/null
+      status=$?
+      if [ $status -eq 0 -a -s _match.s ]; then
+        grep error _match.s > /dev/null
+        status=$?
+        if [ $status -ne 0 ]; then
+          $CC -c _match.s > /dev/null 2> /dev/null
+          status=$?
+          if [ $status -eq 0 -a -f _match.o ]; then
+            echo '-- Using assembly code for match'
+            asmv=1
+            CFLAGS_TST="${CFLAGS_TST} -DASMV"
+            OSDEP_OSZ="${OSDEP_OSZ} ${PROD}/mch_gcc.o"
+          fi
+        fi
+      fi
+      # If using assembler for anything, then check for "_" name prefix.
+      if [ $asmv -ne 0 -o $asm_crc -ne 0 ]; then
+        echo 'Check if compiler generates underlines (CPP, for .S)'
+        echo "int foo() { return 0;}" > conftest.c
+        $AS conftest.c >/dev/null 2>/dev/null
+        nm conftest.o | grep "(^|[^_])foo" >/dev/null 2>/dev/null
+        status=$?
+        [ $status -eq 0 ] && CPP="${CPP} -DNO_UNDERLINE"
+      fi
+      rm -f conftest.S _match.s _match.o _crc_i386.s _crc_i386.o
+
+      # Windows (MinGW) assumes ASMV and ASM_CRC unless dissuaded.
+      if [ $asmv -eq 0 -a $asm_crc -eq 0 ]; then
+        CFLAGS_TST="${CFLAGS_TST} -DNO_ASM"
+      else
+        if [ $asmv -eq 0 ]; then
+          CFLAGS_TST="${CFLAGS_TST} -DNO_ASMV"
+        fi
+        if [ $asm_crc -eq 0 ]; then
+          CFLAGS_TST="${CFLAGS_TST} -DNO_ASM_CRC"
+        fi
+      fi
       ;;
 esac
 
@@ -1222,14 +1298,14 @@ fi
 # LZMA compression.  (User must request: "LZMA=1".)
 if [ -n "${LZMA}" ]; then
   echo "Check LZMA compression support"
-  if [ -d "lzma" ]; then
-    echo "  Check for LZMA header file in lzma"
-    if [ -f "lzma/LzmaDec.h" ]; then
+  if [ -d "szip" ]; then
+    echo "  Check for LZMA header file in szip/"
+    if [ -f "szip/LzmaDec.h" ]; then
       cat > conftest.c << _EOF_
+#include "szip/LzmaEnc.h"
 int main()
 {
    typedef int zoff_t;
-#include "lzma/LzmaEnc.h"
 #ifndef LZMA_SUPPORT
    forget it
 #endif
@@ -1246,15 +1322,15 @@ _EOF_
         echo "-- Including LZMA compression support"
         echo "-- Building liblzma.a in ${PROD}"
       else
-        echo "^^ LZMA test build failed. Check lzma directory"
+        echo "^^ LZMA test build failed. Check szip directory"
         echo "^^ Unable to include LZMA compression support"
       fi
     else
-      echo "^^ LZMA source code not found in lzma directory"
+      echo "^^ LZMA source code not found in szip directory"
       echo "^^ Unable to include LZMA compression support"
     fi
   else
-    echo "^^ Directory lzma not found"
+    echo "^^ Directory szip not found"
     echo "^^ Unable to include LZMA compression support"
   fi
 else
@@ -1267,14 +1343,14 @@ fi
 # PPMd compression.  (User must request: "PPMD=1".)
 if [ -n "${PPMD}" ]; then
   echo "Check PPMd compression support"
-  if [ -d "lzma" ]; then
-    echo "  Check for PPMd header file in lzma"
-    if [ -f "lzma/Ppmd.h" ]; then
+  if [ -d "szip" ]; then
+    echo "  Check for PPMd header file in szip/"
+    if [ -f "szip/Ppmd.h" ]; then
       cat > conftest.c << _EOF_
+#include "szip/Ppmd.h"
 int main()
 {
    typedef int zoff_t;
-#include "lzma/Ppmd.h"
 #ifndef PPMD_SUPPORT
    forget it
 #endif
@@ -1291,15 +1367,15 @@ _EOF_
         echo "-- Including PPMd compression support"
         echo "-- Building libppmd.a in ${PROD}"
       else
-        echo "^^ PPMd test build failed. Check lzma directory"
+        echo "^^ PPMd test build failed. Check szip directory"
         echo "^^ Unable to include PPMd compression support"
       fi
     else
-      echo "^^ PPMD source code not found in lzma directory"
+      echo "^^ PPMD source code not found in szip directory"
       echo "^^ Unable to include PPMd compression support"
     fi
   else
-    echo "^^ Directory lzma not found"
+    echo "^^ Directory szip not found"
     echo "^^ Unable to include PPMd compression support"
   fi
 else
@@ -1511,6 +1587,15 @@ _EOF_
   fi
 else
   echo "ZLIB not used"
+fi
+
+#------------------------------------------------------------------------------
+# H') Configure Zip object library.
+#------------------------------------------------------------------------------
+# Zip object library.  (User must request: "LIBZIP=1".)
+if [ -n "${LIBZIP}" ]; then
+  LIB_ZIP="libizzip.a"
+  echo "-- Building Zip object library (${LIB_ZIP})"
 fi
 
 #------------------------------------------------------------------------------
@@ -2340,10 +2425,13 @@ echo "CC=\"${CC}\" CF=\"${CFLAGS}\"" \
      "LIB_LZMA=\"${LIB_LZMA}\"" \
      "LIB_PPMD=\"${LIB_PPMD}\"" \
      "LIB_Z=\"${LIB_Z}\"" \
+     "LIB_ZIP=\"${LIB_ZIP}\"" \
      "MK_BZ=\"${MK_BZ}\"" \
      "OSDEP_H=\"${OSDEP_H}\"" \
-     "OSDEP_OC=\"${OSDEP_OC}\"" \
-     "OSDEP_OS=\"${OSDEP_OS}\"" \
+     "OSDEP_OCU=\"${OSDEP_OCU}\"" \
+     "OSDEP_OCZ=\"${OSDEP_OCZ}\"" \
+     "OSDEP_OSU=\"${OSDEP_OSU}\"" \
+     "OSDEP_OSZ=\"${OSDEP_OSZ}\"" \
      "PGMEXT=\"${PGMEXT}\" DLLEXT=\"${DLLEXT}\"" \
      "BINDIR=\"${BINDIR}\" BINPERMS=\"${BINPERMS}\"" \
      "MANDIR=\"${MANDIR}\" MANPERMS=\"${MANPERMS}\"" \
