zip 3.0f31 Beta
Origin: http://antinode.info/ftp/info-zip//zip30f31

diff --git a/unix/configure b/unix/configure
--- a/unix/configure
+++ b/unix/configure
@@ -13,13 +13,16 @@ trap "rm -f conftest* core a.out; exit 1" 1 2 3 15
 
 CC=${1-cc}
 CFLAGS=${2-"-I. -DUNIX"}
-IZ_BZIP2=${3-}
 LFLAGS1=''
 LFLAGS2=''
 LN="ln -s"
 
-CFLAGS_BZ=''
 CFLAGS_OPT=''
+
+# bzip2
+IZ_BZIP2=${3-}
+CFLAGS_BZ=''
+
 echo "Check C compiler type (optimization option)"
 cat > conftest.c << _EOF_
 int main()
@@ -54,53 +57,113 @@ _EOF_
   fi
 fi
 
+# optimization flags
 if test -n "${CFLAGS_OPT}"; then
   CFLAGS="${CFLAGS} ${CFLAGS_OPT}"
   CFLAGS_BZ="${CFLAGS_BZ} ${CFLAGS_OPT}"
 fi
 
+
+# bzip2
+
 CC_BZ="${CC}"
 LIB_BZ=''
 echo "Check bzip2 support"
 if test -n "${IZ_BZIP2}"; then
+  echo "  Check for bzip2 files in IZ_BZIP2 (${IZ_BZIP2})"
+  BZ_BAD=''
   if test -f "${IZ_BZIP2}/libbz2.a"; then
 #
-#   A bzip2 library built properly ("BZ_NO_STDIO") should have an
+#   A bzip2 library built with BZ_NO_STDIO should have an
 #   unresolved external, "bz_internal_error".  The default,
 #   full-function library will not mention it.
 #
     nm ${IZ_BZIP2}/libbz2.a | grep bz_internal_error > /dev/null
     if test $? -eq 0; then
-      echo "  Found bzip2 library, ${IZ_BZIP2}/libbz2.a."
+      echo "    Found bzip2 BZ_NO_STDIO library, ${IZ_BZIP2}/libbz2.a."
     else
-      echo "  Found bzip2 library, ${IZ_BZIP2}/libbz2.a,"
-      echo "  but it seems not to be built with the BZ_NO_STDIO option."
-      echo "  Please see the Zip installation instructions."
+      echo "    Found bzip2 library, ${IZ_BZIP2}/libbz2.a,"
+      echo "      but library not compiled with BZ_NO_STDIO."
+      echo "    WARNING:  For proper error handling, we recommend using"
+      echo "    a bzip2 library compiled with BZ_NO_STDIO defined."
+      echo "    Please see the Zip installation instructions in bzip2/install.txt."
+      echo "    Continuing anyway with standard bzip2 library..."
+    fi
+    if test -f "${IZ_BZIP2}/bzlib.h"; then
+      CFLAGS="${CFLAGS} -I${IZ_BZIP2} -DBZIP2_SUPPORT"
+      LFLAGS2="${LFLAGS2} -L${IZ_BZIP2} -lbz2"
+      echo "    Found bzip2 files.  Building with bzip2 support."
+    else
+      echo "    ${IZ_BZIP2}/bzlib.h not found."
+      BZ_BAD='bad'
     fi
   else
-    if test -f "${IZ_BZIP2}/bzlib.h"; then
-      echo "  Found bzip2 source in ${IZ_BZIP2}."
-    else
-      echo "  Can't find bzlib.h or libbz2.a in ${IZ_BZIP2}."
-      echo "  No bzip2 support is possible."
-      IZ_BZIP2=''
-    fi
+    echo "    ${IZ_BZIP2}/libbz2.a not found"
+    BZ_BAD='bad'
   fi
-#
-# If bzip2 support is (still) enabled, then arrange to build a
-# BZ_NO_STDIO bzip2 object library using the same compiler and
-# optimization option as used for Zip, and to compile and link Zip with
-# bzip2 support.
-#
-  if test -n "${IZ_BZIP2}"; then
-    CFLAGS_BZ="${CFLAGS_BZ} -DBZ_NO_STDIO"
-    LIB_BZ="${IZ_BZIP2}/libbz2.a"
-    CFLAGS="${CFLAGS} -I${IZ_BZIP2} -DBZIP2_SUPPORT"
-    LFLAGS2="${LFLAGS2} -L${IZ_BZIP2} -lbz2"
+  if test -n "${BZ_BAD}"; then
+    echo "  User-specified IZ_BZIP2 is incomplete.  Building WITHOUT bzip2 support."
+    echo "  Please see the Zip installation instructions in bzip2/install.txt."
+    IZ_BZIP2=''
   fi
 else
-  echo "  No bzip2 support was requested (\"IZ_BZIP2\")."
+  IZ_BZIP2=./bzip2
+  echo "  Check for bzip2 files in ${IZ_BZIP2} directory"
+  if test -f "${IZ_BZIP2}/libbz2.a"; then
+    nm ${IZ_BZIP2}/libbz2.a | grep bz_internal_error > /dev/null
+      if test $? -eq 0; then
+      echo "    Found bzip2 BZ_NO_STDIO library, ${IZ_BZIP2}/libbz2.a."
+    else
+      echo "    Found bzip2 library, ${IZ_BZIP2}/libbz2.a,"
+      echo "      but library not compiled with BZ_NO_STDIO."
+      echo "    WARNING:  For proper error handling, we recommend using"
+      echo "    a bzip2 library compiled with BZ_NO_STDIO defined."
+      echo "    Please see the Zip installation instructions in bzip2/install.txt."
+      echo "    Continuing anyway with standard bzip2 library..."
+    fi
+  fi
+  if test -f "${IZ_BZIP2}/bzlib.h" -a -f "${IZ_BZIP2}/libbz2.a"; then
+    CFLAGS="${CFLAGS} -I${IZ_BZIP2} -DBZIP2_SUPPORT"
+    LFLAGS2="${LFLAGS2} -L${IZ_BZIP2} -lbz2"
+    echo "    Found bzip2 files.  Building with bzip2 support."
+  else
+    if test -f "${IZ_BZIP2}/bzlib.c"; then
+      echo "  Found bzip2 source in ${IZ_BZIP2} directory."
+      echo "  Will try to build a bzip2 library from source, and use that."
+#
+# Arrange to build a BZ_NO_STDIO bzip2 object library using the
+# same compiler and optimization options as used for Zip, and
+# to compile and link Zip with bzip2.
+#
+      CFLAGS_BZ="${CFLAGS_BZ} -DBZ_NO_STDIO"
+      LIB_BZ="bzip2/libbz2.a"
+      CFLAGS="${CFLAGS} -I${IZ_BZIP2} -DBZIP2_SUPPORT"
+      LFLAGS2="${LFLAGS2} -L${IZ_BZIP2} -lbz2"
+    else
+      echo "  Check if OS already has bzip2 library installed"
+      cat > conftest.c << _EOF_
+#include "bzlib.h"
+int main()
+{
+  bz_stream strm;
+  BZ2_bzCompressEnd(&strm);
+  return 0;
+}
+_EOF_
+      $CC $CFLAGS -o conftest conftest.c -lbz2 > /dev/null 2>/dev/null
+      if test $? -eq 0; then
+        echo "  OS supports bzip2.  Building with bzip2 support."
+        CFLAGS="${CFLAGS} -DBZIP2_SUPPORT"
+        LFLAGS2="${LFLAGS2} -lbz2"
+      else
+        echo "  OS support test for bzip2 failed.  (Missing bzlib.h or libbz2.a,"
+        echo "  bad library path, ...?)  Building WITHOUT bzip2 support."
+        IZ_BZIP2=''
+      fi
+    fi
+  fi
 fi
+
 
 echo Check for the C preprocessor
 # on SVR4, cc -E does not produce correct assembler files. Need /lib/cpp.
